import Note from './components/Note'

const App = ({ notes }) => {
  return (
    <div>
      <h1>Notes</h1>
      <ul>
        {notes.map(note => 
          <Note key={note.id} note={note} />   // core idea is giving key to the elements generated by map
        )}
      </ul>
    </div>
  )
}

export default App
